app:
    service_addr: "0.0.0.0:50054"
db:
  url: "postgres://postgres:uibricks2020Studio@uibricks-studio-dev.cngeo4lavlog.us-west-2.rds.amazonaws.com:5432/postgres?sslmode=disable"
  schema: "project"
redis:
  host: "uibricks-redis"
  port: "6379"
  pwd: ""
  db: "0"
rabbitMq:
  host: "uibricks-rabbitmq"
  port: "5672"
  user: "guest"
  pwd: "guest"
  orchestrator_queue_name: "orchestrator_queue"
  mapping_queue_name: "mapping_queue"
  queue_prefix: "project_reply"
prometheus:
  port: "2112"